import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hero from './Hero'

import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
     
    </div>
  )
}
